"""code error

Revision ID: 2d8fe1ed7662
Revises: 53b34e615282
Create Date: 2023-11-26 04:08:40.611543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d8fe1ed7662'
down_revision = '53b34e615282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_course_association', schema=None) as batch_op:
        batch_op.drop_constraint('courses.id', type_='foreignkey')
        batch_op.create_foreign_key('code.snippet', 'code_snippets', ['code_snippet'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_course_association', schema=None) as batch_op:
        batch_op.drop_constraint('courses.id', type_='foreignkey')
        batch_op.create_foreign_key('code.snippet', 'code_snippets', ['code_snippet'], ['code_snippet'])

    # ### end Alembic commands ###
