"""removed some models for the next version

Revision ID: 53b34e615282
Revises: 
Create Date: 2023-11-26 03:23:27.749786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b34e615282'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_electronic_circuit_association')
    op.drop_table('course_images_association')
    op.drop_table('file_architecture')
    op.drop_table('key_aspects')
    op.drop_table('problem_key_aspects')
    op.drop_table('course_visual_3d_complex_association')
    op.drop_table('visual_3d_complex')
    op.drop_table('course_file_architecture_association')
    op.drop_table('images')
    op.drop_table('electronic_circuit_designs')
    op.drop_table('problem_key_aspects_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_key_aspects_association',
    sa.Column('course_id', sa.INTEGER(), nullable=True),
    sa.Column('key_aspects_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['key_aspects_id'], ['key_aspects.id'], )
    )
    op.create_table('electronic_circuit_designs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('design_url', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_file_architecture_association',
    sa.Column('courses_id', sa.INTEGER(), nullable=True),
    sa.Column('file_architecture_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['courses_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['file_architecture_id'], ['file_architecture.id'], )
    )
    op.create_table('visual_3d_complex',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('visual_url', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_visual_3d_complex_association',
    sa.Column('courses_id', sa.INTEGER(), nullable=True),
    sa.Column('visual_3d_complex_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['courses_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['visual_3d_complex_id'], ['visual_3d_complex.id'], )
    )
    op.create_table('problem_key_aspects',
    sa.Column('courses_id', sa.INTEGER(), nullable=True),
    sa.Column('aspect_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['aspect_id'], ['key_aspects.id'], ),
    sa.ForeignKeyConstraint(['courses_id'], ['courses.id'], )
    )
    op.create_table('key_aspects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('aspect', sa.VARCHAR(), nullable=True),
    sa.Column('consequence', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_architecture',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filesys', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_images_association',
    sa.Column('courses_id', sa.INTEGER(), nullable=True),
    sa.Column('image_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['courses_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], )
    )
    op.create_table('course_electronic_circuit_association',
    sa.Column('courses_id', sa.INTEGER(), nullable=True),
    sa.Column('electronic_circuit_designs_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['courses_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['electronic_circuit_designs_id'], ['electronic_circuit_designs.id'], )
    )
    # ### end Alembic commands ###
